name: Create Sublime Package

on:
  release:
    types:
      - created

jobs:
  package:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Zip Folder
        run: zip -r "SDML.sublime-package" . -x ".git/*" -x ".github/*" -x ".gitignore" -x "images/" -x "install.sh"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "SDML.sublime-package"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
