name: Create Sublime Package

on:
  release:
    types:
      - created

env:
  GIT_IGNORE: -x ".git/*" -x ".github/*" -x ".gitignore"
  MAC_IGNORE: -x ".DS_Store"
  EMACS_IGNORE: -x "*~" -x ".*.~undo-tree~"
  IGNORE: -x "images/" -x "install.sh"
  PACKAGE_NAME: SDML


jobs:
  package:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Zip Folder
        run: zip -r $PACKAGE_NAME.sublime-package . $GIT_IGNORE $MAC_IGNORE $EMACS_IGNORE $IGNORE

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: $PACKAGE_NAME.sublime-package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
